// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBd4Rg6IrIlyGEy8aXOLq0oRl4Wpax4JA4',
    appId: '1:492672993820:web:9286cc6f5fcc0134b66dd9',
    messagingSenderId: '492672993820',
    projectId: 'carnival-fine-dine-8a8a9',
    authDomain: 'carnival-fine-dine-8a8a9.firebaseapp.com',
    storageBucket: 'carnival-fine-dine-8a8a9.firebasestorage.app',
    measurementId: 'G-Q3T2C5EMTM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyGS0dEbbVppe4x9S-wnOLhD7XtNRy-Io',
    appId: '1:492672993820:android:a9ebb833ff88c41ab66dd9',
    messagingSenderId: '492672993820',
    projectId: 'carnival-fine-dine-8a8a9',
    storageBucket: 'carnival-fine-dine-8a8a9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBF5HsIEHj1EZf2LUb9x7E4TIEV8zs0xI4',
    appId: '1:492672993820:ios:b44be0e2865fc1b1b66dd9',
    messagingSenderId: '492672993820',
    projectId: 'carnival-fine-dine-8a8a9',
    storageBucket: 'carnival-fine-dine-8a8a9.firebasestorage.app',
    iosBundleId: 'com.example.carnivalFineDining',
  );
}
