// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyQ6OyTZ-EM5JNyWEWEB7hquHlYvJ0-Ec',
    appId: '1:325453903065:web:22c2ec52c19212cb953ac8',
    messagingSenderId: '325453903065',
    projectId: 'carnival-finedining-restaurant',
    authDomain: 'carnival-finedining-restaurant.firebaseapp.com',
    storageBucket: 'carnival-finedining-restaurant.firebasestorage.app',
    measurementId: 'G-6XXLGLEV0E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEXijNPqUbgGDd_aDTFchIkbyONg6YfSs',
    appId: '1:325453903065:android:8eb7ae891f56d527953ac8',
    messagingSenderId: '325453903065',
    projectId: 'carnival-finedining-restaurant',
    storageBucket: 'carnival-finedining-restaurant.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBL4x6QxDaUowxikFeQl5r2t9P4FlppH0U',
    appId: '1:325453903065:ios:1cb25655c124e793953ac8',
    messagingSenderId: '325453903065',
    projectId: 'carnival-finedining-restaurant',
    storageBucket: 'carnival-finedining-restaurant.firebasestorage.app',
    iosBundleId: 'com.example.carnivalFineDiningRestaurantProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBL4x6QxDaUowxikFeQl5r2t9P4FlppH0U',
    appId: '1:325453903065:ios:1cb25655c124e793953ac8',
    messagingSenderId: '325453903065',
    projectId: 'carnival-finedining-restaurant',
    storageBucket: 'carnival-finedining-restaurant.firebasestorage.app',
    iosBundleId: 'com.example.carnivalFineDiningRestaurantProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyQ6OyTZ-EM5JNyWEWEB7hquHlYvJ0-Ec',
    appId: '1:325453903065:web:7679034f8a6131d4953ac8',
    messagingSenderId: '325453903065',
    projectId: 'carnival-finedining-restaurant',
    authDomain: 'carnival-finedining-restaurant.firebaseapp.com',
    storageBucket: 'carnival-finedining-restaurant.firebasestorage.app',
    measurementId: 'G-QX3NCYKWTX',
  );
}
